var url_path = pm.request.url.getPathWithQuery();
var url_method = pm.request.method;
var space = " "; 
var newLine = "\n";
var method = url_method;
var url = url_path;
var timestamp = String(new Date().getTime());
var accessKey = pm.environment.get("ncp_accessKey_dev_ibk");
var secretKey = pm.environment.get("ncp_secretKey_dev_ibk");
var hmac = CryptoJS.algo.HMAC.create(CryptoJS.algo.SHA256, secretKey);
hmac.update(method);
hmac.update(space);
hmac.update(url);
hmac.update(newLine);
hmac.update(timestamp);
hmac.update(newLine);
hmac.update(accessKey);
var hash = hmac.finalize();
pm.environment.set("url_path",url_path);
pm.environment.set("url_method",url_method);
pm.environment.set("x-ncp-apigw-timestamp",timestamp);
pm.environment.set("x-ncp-iam-access-key",accessKey);
pm.environment.set("x-ncp-apigw-signature-v2",hash.toString(CryptoJS.enc.Base64));